# Generated by Django 2.2.1 on 2019-05-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node_spi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.TextField()),
                ('MAC', models.TextField()),
                ('RSSI', models.TextField()),
                ('TIME', models.TextField()),
                ('DIST', models.TextField()),
            ],
        ),
    ]
